export enum ERoutePath {
  LOGIN = "/login",
  FORGOT_PASSWORD = "/forgot-password",
  REGISTER = "/register",
  HOME = "/home",
  PRODUCTS = "/products",
  PRODUCT_DETAIL = "/products/:id",
  MY_CART = "/my-cart",
  CART_CHECKOUT = "/my-cart/orders",
  PROFILE = "/profile",
  MY_ORDER = "/my-order",
  DASH_BOARD_USER = "/my-dashboard",
  MY_ALERTS = "/my-dashboard/alerts",
  MY_COMMISSION = "/commissions",
  MARKETPLACE = "/marketplace",
  MY_GENEALOGY = "/my-genealogy",
  CONTACT_US = "/contact-us",
  NEWS = "/news",
  NEWS_SCIENCE = "/news",
  NEWS_SCIENCE_DETAIL = "/news/:id",
  NEWS_HEALTH = "/news/heath",
  ABOUT_US = "/about-us",
  ABOUT_US_VISION = "/about-us/vision",
  ABOUT_US_MESSAGE = "/about-us/founder-message",

  ADMIN_DASHBOARD = "/admin/dashboard",
  ADMIN_BALANCE_TRACKING = "/admin/balance-tracking",
  ADMIN_ORDERS = "/admin/orders",
  ADMIN_ORDERS_DETAIL = "/admin/orders/:id",
  ADMIN_PRODUCTS = "/admin/products",
  ADMIN_PRODUCTS_CREATE = "/admin/products/create",
  ADMIN_PRODUCTS_EDIT = "/admin/products/edit/:id",
  ADMIN_SALES_REPORT = "/admin/sales-report",
  ADMIN_SETTINGS = "/admin/settings",
}
